# Site settings
title: Takuma510
email: takuma510@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  takuma510's blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://takuma510.github.io"
twitter_username: takuma510
github_username:  takuma510

# Build settings
markdown: kramdown
